name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  VERSION: ${{ secrets.DOCKERHUB_USERNAME }}.${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag archeious/unbiasedgeek-com:${{VERSION}}
      - name: Push the tagged Docker image
        run: docker push archeious/unbiasedgeek-com:${{VERSION}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag archeious/unbiasedgeek:latest
      - name: Push the latest Docker image
        run: docker push archeious/unbiasedgeek:latest
